(set-join-check on)
(deftemplate A (slot v))
(deftemplate B (slot v))
(deftemplate C (slot v))
(defrule r (A v ?x) (B v ?x) (C v ?x) => (printout t "J" crlf))
(assert A v 1)
(assert B v 1)
(assert C v 1)
(run)
(assert A v 2)
(assert B v 2)
(assert C v 2)
(run)
